name: "Báo cáo lỗi"
description: "Có điều gì đó ở Doanhanma không diễn ra như bạn mong đợi"
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Lưu ý:
        - Mô tả rõ ràng và ngắn gọn về tiêu đề lỗi (cái gì, ở đâu, khi nào)
        - Không báo cáo các vấn đề chính tả tại đây!
        - Bạn nên bắt đầu bước tái hiện lỗi đầu tiên trên trang chủ
  - type: textarea
    id: repro
    attributes:
      label: "Các bước tái hiện lỗi"
      description: "Hãy hướng dẫn mình từng bước một để kích hoạt lỗi này!"
      placeholder: |
        1. Đi tới ~
        2. Nhấp/Chạm vào ~
        3. Cuộn/Vuốt xuống ~
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: detail-result
    attributes:
      label: "Chi tiết về lỗi"
      description: "Nói cho mình biết chuyện gì đã xảy ra và những gì bạn mong đợi"
      placeholder: "ví dụ: Biểu tượng con trỏ chuột hình bàn tay xuất hiện khi di chuột qua liên kết 'Sửa bài viết' nhưng khi nhấp vào lại không có bất kỳ phản hồi nào trả về. Theo mong đợi, liên kết được nhấp vào sẽ chuyển hướng người dùng tới một trang chỉnh sửa bài viết hiện tại." 
      render: bash
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: "Lỗi này xảy ra trên trình duyệt nào?"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: more-info
    attributes:
      label: "Thông tin bổ sung"
      description: "Các thông tin khác như: phiên bản hệ điều hành thiết bị, ảnh chụp màn hình, nhật ký trình duyệt, ... Bạn có thể sao chép và dán tại đây!"
  - type: input
    id: contact
    attributes:
      label: "Email liên hệ"
      description: "Phòng trường hợp mình cần thêm thông tin."
      placeholder: "ví dụ: email@example.com"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "*Cảm ơn bạn đã dành thời gian điền vào báo cáo lỗi này!*"

